const mongoose = require("mongoose");
// const deviceInfoSchema = new mongoose.Schema({
//   isYaBrowser: Boolean,
//   isAuthoritative: Boolean,
//   isMobile: Boolean,
//   isMobileNative: Boolean,
//   isTablet: Boolean,
//   isiPad: Boolean,
//   isiPod: Boolean,
//   isiPhone: Boolean,
//   isiPhoneNative: Boolean,
//   isAndroid: Boolean,
//   isAndroidNative: Boolean,
//   isBlackberry: Boolean,
//   isOpera: Boolean,
//   isIE: Boolean,
//   isEdge: Boolean,
//   isIECompatibilityMode: Boolean,
//   isSafari: Boolean,
//   isFirefox: Boolean,
//   isWebkit: Boolean,
//   isChrome: Boolean,
//   isKonqueror: Boolean,
//   isOmniWeb: Boolean,
//   isSeaMonkey: Boolean,
//   isFlock: Boolean,
//   isAmaya: Boolean,
//   isPhantomJS: Boolean,
//   isEpiphany: Boolean,
//   isDesktop: Boolean,
//   isWindows: Boolean,
//   isLinux: Boolean,
//   isLinux64: Boolean,
//   isMac: Boolean,
//   isChromeOS: Boolean,
//   isBada: Boolean,
//   isSamsung: Boolean,
//   isRaspberry: Boolean,
//   isBot: Boolean,
//   isCurl: Boolean,
//   isAndroidTablet: Boolean,
//   isWinJs: Boolean,
//   isKindleFire: Boolean,
//   isSilk: Boolean,
//   isCaptive: Boolean,
//   isSmartTV: Boolean,
//   isUC: Boolean,
//   isFacebook: Boolean,
//   isAlamoFire: Boolean,
//   isElectron: Boolean,
//   silkAccelerated: Boolean,
//   browser: String,
//   version: String,
//   os: String,
//   platform: String,
//   geoIp: {},
//   source: String,
//   isWechat: Boolean,
//   ip: String,
// });
const urlSchema = new mongoose.Schema(
  {
    shortId: {
      type: String,
      required: true,
      unique: true,
    },
    redirectURL: {
      type: String,
      required: true,
    },
    visitHistory: [
      {
        timestamp: { type: Date },
        deviceInfo: {
          isYaBrowser: mongoose.Schema.Types.Mixed,
          isAuthoritative: mongoose.Schema.Types.Mixed,
          isMobile: mongoose.Schema.Types.Mixed,
          isMobileNative: mongoose.Schema.Types.Mixed,
          isTablet: mongoose.Schema.Types.Mixed,
          isiPad: mongoose.Schema.Types.Mixed,
          isiPod: mongoose.Schema.Types.Mixed,
          isiPhone: mongoose.Schema.Types.Mixed,
          isiPhoneNative: mongoose.Schema.Types.Mixed,
          isAndroid: mongoose.Schema.Types.Mixed,
          isAndroidNative: mongoose.Schema.Types.Mixed,
          isBlackberry: mongoose.Schema.Types.Mixed,
          isOpera: mongoose.Schema.Types.Mixed,
          isIE: mongoose.Schema.Types.Mixed,
          isEdge: mongoose.Schema.Types.Mixed,
          isIECompatibilityMode: mongoose.Schema.Types.Mixed,
          isSafari: mongoose.Schema.Types.Mixed,
          isFirefox: mongoose.Schema.Types.Mixed,
          isWebkit: mongoose.Schema.Types.Mixed,
          isChrome: mongoose.Schema.Types.Mixed,
          isKonqueror: mongoose.Schema.Types.Mixed,
          isOmniWeb: mongoose.Schema.Types.Mixed,
          isSeaMonkey: mongoose.Schema.Types.Mixed,
          isFlock: mongoose.Schema.Types.Mixed,
          isAmaya: mongoose.Schema.Types.Mixed,
          isPhantomJS: mongoose.Schema.Types.Mixed,
          isEpiphany: mongoose.Schema.Types.Mixed,
          isDesktop: mongoose.Schema.Types.Mixed,
          isWindows: mongoose.Schema.Types.Mixed,
          isLinux: mongoose.Schema.Types.Mixed,
          isLinux64: mongoose.Schema.Types.Mixed,
          isMac: mongoose.Schema.Types.Mixed,
          isChromeOS: mongoose.Schema.Types.Mixed,
          isBada: mongoose.Schema.Types.Mixed,
          isSamsung: mongoose.Schema.Types.Mixed,
          isRaspberry: mongoose.Schema.Types.Mixed,
          isBot: mongoose.Schema.Types.Mixed,
          isCurl: mongoose.Schema.Types.Mixed,
          isAndroidTablet: mongoose.Schema.Types.Mixed,
          isWinJs: mongoose.Schema.Types.Mixed,
          isKindleFire: mongoose.Schema.Types.Mixed,
          isSilk: mongoose.Schema.Types.Mixed,
          isCaptive: mongoose.Schema.Types.Mixed,
          isSmartTV: mongoose.Schema.Types.Mixed,
          isUC: mongoose.Schema.Types.Mixed,
          isFacebook: mongoose.Schema.Types.Mixed,
          isAlamoFire: mongoose.Schema.Types.Mixed,
          isElectron: mongoose.Schema.Types.Mixed,
          silkAccelerated: mongoose.Schema.Types.Mixed,
          browser: mongoose.Schema.Types.Mixed,
          version: mongoose.Schema.Types.Mixed,
          os: mongoose.Schema.Types.Mixed,
          platform: mongoose.Schema.Types.Mixed,
          geoIp: {},
          source: mongoose.Schema.Types.Mixed,
          isWechat: mongoose.Schema.Types.Mixed,
          ip: mongoose.Schema.Types.Mixed,
        },
      },
    ],
  },
  { timestamps: true }
);

const URL = mongoose.model("url", urlSchema);

module.exports = URL;
